on:
  push:
    branches: master

name: Render README

jobs:
  render:
    name: Render README
    runs-on: ubuntu-latest
    steps: |
      git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
      git push origin || echo "No changes to commit"
